### ISSUE TITLE
roswww cannot be installed with rosbridge as there is a conflict

### ISSUE THREAD

**Issue by vrabaud** [tork-a/roswww#1]
They both contain tornado and it is installed by both. Just install the two packages to reproduce.

**Comment by 130s** [comment]
Yes I'm aware of that. Refrain from installing roswww until this gets settled..

**Comment by 130s** [comment]
Besides [this commit](0c4b6cf8eb1eac36ba49c110312505bbe745097f) that removes overlapping files, this package [will be removed from rosdistro](https://github.com/ros/rosdistro/pull/2619) shortly.
