### ISSUE TITLE
Browser keeps trying to connect

### ISSUE THREAD

**Issue by 130s** [tork-a/roswww#14]
Continued from https://github.com/tork-a/roswww/pull/13#issuecomment-68227901
Confirmed with de2d9e00e96932d1da4178900fc7fee021dc63f7 on Indigo, Trusty

Error description updated:

`$ rosrun roswww webserver.py` then accessing http://localhost:8000 doesn't return (web browser keeps trying on and on). When I kill webserver.py's process, browser immediately shows "server not found", so I assume the browser is able to connect to the webserver (webserver log file might help here..).

**Comment by jihoonl** [comment]
It seems like tornado problem which rosbridge is also experiencing. I am in the middle of reverting tornado back into rosbridge_server. 

Ref : https://github.com/RobotWebTools/rosbridge_suite/issues/160

**Comment by 130s** [comment]
With the revert https://github.com/tork-a/roswww/issues/15 this issue has become invalid for now.
