### ISSUE TITLE
Abandon the repository?

### ISSUE THREAD

**Issue by 130s** [tork-a/roswww#3]
Since `roswww` is now merged into `rwt_ros` (see https://github.com/tork-a/rwt_ros/issues/2#issuecomment-29359589), keeping a separate repository might be just confusing. `roswww` used to be released into ROS Groovy too, but it [was withdrawn](https://github.com/ros/rosdistro/pull/2619).

**Comment by jihoonl** [comment]
I wonder if `roswww` is no longer maintained. If yes, could I take it back?  I would like to revive the package with some api changes.

**Comment by 130s** [comment]
@jihoonl we've moved `roswww` under [rwt_ros](https://github.com/tork-a/rwt_ros/tree/hydro-devel/roswww). We're happy to maintain it there (and of course accepting PRs) but we're open to suggestions as well.

The reason we integrated roswww into another package suite was only because we then thought a bit verbose to have many web-related repositories, according to https://github.com/tork-a/rwt_ros/issues/2#issuecomment-29359589 (in Japanese sorry). `rwt_ros` is intended as an app layer framework laid on top of `rwt`, and is slowly developed (a project is going on now). Now, however, I reviewed the decision and I started feeling roswww doesn't necessarily lie under rwt umbrella so it might be better to separate it back (that allows us to DEB-release easily like it used to be).

**Comment by jihoonl** [comment]
It is good to keep in the rwt_ros branch as long as it is released as deb with clean dependency chain. :)

I would like to propose some changes to use roswww as catkin_based webserver which does not bring ros_comm dependency. I will create other issue to propose changes in rwt_ros.

**Comment by jihoonl** [comment]
I was just curious because it was not release in indigo. :wink:

**Comment by jihoonl** [comment]
BTW. Wouldn't it be better to release only roswww? 

Javascript libs like roslibjs and ros2djs could easily be out of sync from upstream..

**Comment by jihoonl** [comment]
roswww update proposal https://github.com/tork-a/rwt_ros/issues/13

**Comment by 130s** [comment]
> rwt_ros branch as long as it is released as deb with clean dependency chain. :)

Releasing as DEB is actually not in the plan for `rwt_ros` yet (needs to happen. Related: https://github.com/tork-a/rwt_ros/issues/3).

> BTW. Wouldn't it be better to release only roswww?

Yeah. That's what I wanted to mean in https://github.com/tork-a/roswww_pkg/issues/3#issuecomment-65961490
I guess we rejuvenate roswww_pkg as standalone repository so that it can be  released separately. I can do so only later this week but I or someone can review pull requests that'll make it happen faster.

> Javascript libs like roslibjs and ros2djs could easily be out of sync from upstream..

I might be too behind web-development scene to figure out what you mean by this.

**Comment by 130s** [comment]
@jihoonl Actually I invited you for a write access if you feel like ;)

**Comment by jihoonl** [comment]
Great thanks!

**Comment by 130s** [comment]
We're not abandoning this repository.
