### ISSUE TITLE
Questions about this package... sample code? only for static pages?

### ISSUE THREAD

**Issue by pitosalas** [tork-a/roswww#41]
I don't know where the community for this package lives, so I am asking here even though this is not an issue. I am looking to host a simple web server on my Ros robot. Basically responding to HTTP GETs returning status html pages, or to HTTP POSTs to tell the robot to do something. This will allow me to create a non-ROS client on a mobile or just a web browser. 

- I am not clear whether this library only serves up static html pages or can respond with custom code to any http request, executing ROS code as a result.

- Can you point me to a sample where this package is used so I can see how to do various things?

**Comment by 130s** [comment]
I assume [this thread](https://groups.google.com/forum/#!topic/robot-web-tools/rdtOk3f7LeI) you started already answers to you.
