### ISSUE TITLE
Melodic version

### ISSUE THREAD

**Issue by athackst** [tork-a/roswww#47]
Is there any plan to release a melodic version?

**Comment by k-okada** [comment]
Sure,  should we merge 
https://github.com/tork-a/roswww/pull/45 before melodic release ?

**Comment by athackst** [comment]
SGTM

Can I do anything to help the other PR land?

**Comment by k-okada** [comment]
ok, done  https://github.com/ros/rosdistro/pull/20641

--
◉ Kei Okada



2019年3月20日(水) 14:01 Allison Thackston <notifications@github.com>:

**Comment by dirk-thomas** [comment]
Can this ticket be closed?
