### ISSUE TITLE
rename the branches

### ISSUE THREAD

**Issue by jihoonl** [tork-a/roswww#7]
Just curios. If not how about renaming branch as something general? like `develop` in rosbridge_suite?

**Comment by 130s** [comment]
There has always been a discussion about this but here's my opinion: in general for ROS-dependent packages separating branches clearly tells which ROS-distro is NOT supported. With the case of `roswww` it needs `tornado` that wasn't provided by upstream in Groovy AFAIK but now it is provided by `rosbridge_tools` (correct?) in Hydro onward.

**Comment by jihoonl** [comment]
Since groovy is end of life, we can leave `groovy-devel` and `fuerte-devel` branches as it is. I meant to have a branch to maintain hydro and above. Just as rosbridge_suite has `fuerte-devel` and `groovy-devel` as history branch and use `develop` for hydro and above.

**Comment by 130s** [comment]
Help me to understand; so in your idea, use for instance `develop` as a master and in case there'd be a difference in `indigo` and newer distro (say jade), create `indigo-devel` as a history?

**Comment by jihoonl** [comment]
Ah to be clear, This is how rosbridge_suite is maintaining each distribution

**Release - Branch**
Fuerte : fuerte-devel
Groovy: groovy-devel

**release branch - develop branch**
Hydro:       master, develop
Indigo:       master, develop
Jade :  master, develop

So we can maintain three distributions with one branch. Less maintain job. I think the issue name confuses you. I have rename the issue.

**Comment by 130s** [comment]
Ok, think I got it. 
- So I've created `develop` branch as suggested, made it a default branch.
- `hydro-devel` branch is gone. Whenever necessary, we can re-create it as a history branch.

So **whoever has cloned this repo, please update the default branch**.
